import { useRef } from 'react';
import { Download } from 'lucide-react';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import { type ProcessedTransaction, useAnalytics } from '../utils/analytics';
import { SummaryCards } from './SummaryCards';
import { Insights } from './Insights';
import { ExpensesPieChart } from './Charts/ExpensesPieChart';
import { MonthlyBarChart } from './Charts/MonthlyBarChart';
import { TrendLineChart } from './Charts/TrendLineChart';

interface DashboardProps {
    transactions: ProcessedTransaction[];
    onReset: () => void;
}

export function Dashboard({ transactions, onReset }: DashboardProps) {
    const analytics = useAnalytics(transactions);
    const dashboardRef = useRef<HTMLDivElement>(null);

    const handleExport = async () => {
        if (!dashboardRef.current) return;

        // Simple improved quality export
        const canvas = await html2canvas(dashboardRef.current, {
            scale: 2,
            useCORS: true,
            logging: false,
            backgroundColor: '#f9fafb' // tailwind gray-50
        });

        const imgData = canvas.toDataURL('image/png');
        const pdf = new jsPDF({
            orientation: 'portrait',
            unit: 'px',
            format: [canvas.width, canvas.height]
        });

        pdf.addImage(imgData, 'PNG', 0, 0, canvas.width, canvas.height);
        pdf.save('bank-wrapped.pdf');
    };

    return (
        <div className="min-h-screen bg-gray-50 p-4 md:p-8">
            {/* Header Actions */}
            <div className="max-w-7xl mx-auto flex justify-between items-center mb-8">
                <h1 className="text-3xl font-bold text-gray-900 tracking-tight">
                    2025 <span className="text-blue-600">Wrapped</span>
                </h1>
                <div className="flex gap-3">
                    <button
                        onClick={onReset}
                        className="px-4 py-2 text-sm font-medium text-gray-600 hover:text-gray-900 bg-white border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors"
                    >
                        Upload New
                    </button>
                    <button
                        onClick={handleExport}
                        className="px-4 py-2 text-sm font-medium text-white bg-blue-600 rounded-lg hover:bg-blue-700 transition-colors flex items-center gap-2 shadow-sm"
                    >
                        <Download size={16} /> Export PDF
                    </button>
                </div>
            </div>

            {/* Printable Area */}
            <div ref={dashboardRef} className="max-w-7xl mx-auto space-y-8 bg-gray-50 p-4 -m-4">

                <SummaryCards
                    totalInflow={analytics.totalInflow}
                    totalExpense={analytics.totalExpense}
                />

                <Insights
                    topCategory={analytics.insights.topCategory}
                    highestSpendingMonth={analytics.insights.highestSpendingMonth}
                    netSavings={analytics.insights.netSavings}
                />

                <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                    <ExpensesPieChart data={analytics.expensesByCategory} />
                    <MonthlyBarChart data={analytics.monthlyData} />
                </div>

                <div className="w-full">
                    <TrendLineChart data={analytics.monthlyData} />
                </div>

                <div className="text-center pt-8 pb-4 text-gray-400 text-sm">
                    Generated by Bank Wrapped App • Private & Secure
                </div>
            </div>
        </div>
    );
}
